{
 "title": "SQL Server and FlashArray",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "sql_instance",
    "label": "SQL Instance",
    "query": {
     "query": "query_result(sqlserver_server_properties_cpu_count{sql_instance=~\".+\"})"
    }
   },
   {
    "name": "instance",
    "label": "FlashArray",
    "query": {
     "query": "query_result(purefa_info{instance=~\".+\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(sqlserver_cpu_sqlserver_process_cpu{sql_instance=~\"^$sql_instance\"}) by (sql_instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Performance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sqlserver_performance{sql_instance=~\"$sql_instance\",counter=\"Page life expectancy\",object=\"SQLServer:Buffer Node\"} ",
     "legendFormat": "{{sql_instance}} - {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Wait Stats (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(20,\n  avg by (sql_instance, wait_type) (\n    irate(sqlserver_waitstats_signal_wait_time_ms{\n      sql_instance=~\"^$sql_instance\",\n      wait_type!~\"(?i)BROKER_EVENTHANDLER|BROKER_RECEIVE_WAITFOR|BROKER_TASK_STOP|BROKER_TO_FLUSH|BROKER_TRANSMITTER|CHECKPOINT_QUEUE|CHKPT|CLR_AUTO_EVENT|CLR_MANUAL_EVENT|CLR_SEMAPHORE|CXCONSUMER|DBMIRROR_DBM_EVENT|DBMIRROR_EVENTS_QUEUE|DBMIRROR_WORKER_QUEUE|DBMIRRORING_CMD|DIRTY_PAGE_POLL|DISPATCHER_QUEUE_SEMAPHORE|EXECSYNC|FSAGENT|FT_IFTS_SCHEDULER_IDLE_WAIT|FT_IFTSHC_MUTEX|HADR_CLUSAPI_CALL|HADR_FILESTREAM_IOMGR_IOCOMPLETION|HADR_LOGCAPTURE_WAIT|HADR_NOTIFICATION_DEQUEUE|HADR_TIMER_TASK|HADR_WORK_QUEUE|KSOURCE_WAKEUP|LAZYWRITER_SLEEP|LOGMGR_QUEUE|MEMORY_ALLOCATION_EXT|ONDEMAND_TASK_QUEUE|PARALLEL_REDO_DRAIN_WORKER|PARALLEL_REDO_LOG_CACHE|PARALLEL_REDO_TRAN_LIST|PARALLEL_REDO_WORKER_SYNC|PARALLEL_REDO_WORKER_WAIT_WORK|PREEMPTIVE_XE_GETTARGETSTATE|PWAIT_ALL_COMPONENTS_INITIALIZED|PWAIT_DIRECTLOGCONSUMER_GETNEXT|QDS_PERSIST_TASK_MAIN_LOOP_SLEEP|QDS_ASYNC_QUEUE|QDS_CLEANUP_STALE_QUERIES_TASK_MAIN_LOOP_SLEEP|QDS_SHUTDOWN_QUEUE|REDO_THREAD_PENDING_WORK|REQUEST_FOR_DEADLOCK_SEARCH|RESOURCE_QUEUE|SERVER_IDLE_CHECK|SLEEP_BPOOL_FLUSH|SLEEP_DBSTARTUP|SLEEP_DCOMSTARTUP|SLEEP_MASTERDBREADY|SLEEP_MASTERMDREADY|SLEEP_MASTERUPGRADED|SLEEP_MSDBSTARTUP|SLEEP_SYSTEMTASK|SLEEP_TASK|SLEEP_TEMPDBSTARTUP|SNI_HTTP_ACCEPT|SOS_WORK_DISPATCHER|SP_SERVER_DIAGNOSTICS_SLEEP|SQLTRACE_BUFFER_FLUSH|SQLTRACE_INCREMENTAL_FLUSH_SLEEP|SQLTRACE_WAIT_ENTRIES|WAIT_FOR_RESULTS|WAITFOR|WAITFOR_TASKSHUTDOWN|WAIT_XTP_RECOVERY|WAIT_XTP_HOST_WAIT|WAIT_XTP_OFFLINE_CKPT_NEW_LOG|WAIT_XTP_CKPT_CLOSE|XE_DISPATCHER_JOIN|XE_DISPATCHER_WAIT|XE_TIMER_EVENT\"\n    }[30s])\n  )\n)",
     "legendFormat": "{{sql_instance}} - {{wait_type}}"
    },
    {
     "expr": "topk(20,\n  avg by (sql_instance, wait_type) (\n    irate(sqlserver_waitstats_resource_wait_time_ms{\n      sql_instance=~\"^$sql_instance\",\n      wait_type!~\"(?i)BROKER_EVENTHANDLER|BROKER_RECEIVE_WAITFOR|BROKER_TASK_STOP|BROKER_TO_FLUSH|BROKER_TRANSMITTER|CHECKPOINT_QUEUE|CHKPT|CLR_AUTO_EVENT|CLR_MANUAL_EVENT|CLR_SEMAPHORE|CXCONSUMER|DBMIRROR_DBM_EVENT|DBMIRROR_EVENTS_QUEUE|DBMIRROR_WORKER_QUEUE|DBMIRRORING_CMD|DIRTY_PAGE_POLL|DISPATCHER_QUEUE_SEMAPHORE|EXECSYNC|FSAGENT|FT_IFTS_SCHEDULER_IDLE_WAIT|FT_IFTSHC_MUTEX|HADR_CLUSAPI_CALL|HADR_FILESTREAM_IOMGR_IOCOMPLETION|HADR_LOGCAPTURE_WAIT|HADR_NOTIFICATION_DEQUEUE|HADR_TIMER_TASK|HADR_WORK_QUEUE|KSOURCE_WAKEUP|LAZYWRITER_SLEEP|LOGMGR_QUEUE|MEMORY_ALLOCATION_EXT|ONDEMAND_TASK_QUEUE|PARALLEL_REDO_DRAIN_WORKER|PARALLEL_REDO_LOG_CACHE|PARALLEL_REDO_TRAN_LIST|PARALLEL_REDO_WORKER_SYNC|PARALLEL_REDO_WORKER_WAIT_WORK|PREEMPTIVE_XE_GETTARGETSTATE|PWAIT_ALL_COMPONENTS_INITIALIZED|PWAIT_DIRECTLOGCONSUMER_GETNEXT|QDS_PERSIST_TASK_MAIN_LOOP_SLEEP|QDS_ASYNC_QUEUE|QDS_CLEANUP_STALE_QUERIES_TASK_MAIN_LOOP_SLEEP|QDS_SHUTDOWN_QUEUE|REDO_THREAD_PENDING_WORK|REQUEST_FOR_DEADLOCK_SEARCH|RESOURCE_QUEUE|SERVER_IDLE_CHECK|SLEEP_BPOOL_FLUSH|SLEEP_DBSTARTUP|SLEEP_DCOMSTARTUP|SLEEP_MASTERDBREADY|SLEEP_MASTERMDREADY|SLEEP_MASTERUPGRADED|SLEEP_MSDBSTARTUP|SLEEP_SYSTEMTASK|SLEEP_TASK|SLEEP_TEMPDBSTARTUP|SNI_HTTP_ACCEPT|SOS_WORK_DISPATCHER|SP_SERVER_DIAGNOSTICS_SLEEP|SQLTRACE_BUFFER_FLUSH|SQLTRACE_INCREMENTAL_FLUSH_SLEEP|SQLTRACE_WAIT_ENTRIES|WAIT_FOR_RESULTS|WAITFOR|WAITFOR_TASKSHUTDOWN|WAIT_XTP_RECOVERY|WAIT_XTP_HOST_WAIT|WAIT_XTP_OFFLINE_CKPT_NEW_LOG|WAIT_XTP_CKPT_CLOSE|XE_DISPATCHER_JOIN|XE_DISPATCHER_WAIT|XE_TIMER_EVENT\"\n    }[30s])\n  )\n)",
     "legendFormat": "{{sql_instance}} - {{wait_type}}"
    }
   ]
  },
  {
   "title": "Data Reads/Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (sql_instance, database_name) (\n  irate(sqlserver_database_io_read_bytes{sql_instance=~\"$sql_instance\"}[30s])\n)\n",
     "legendFormat": "{{sql_instance}} - {{database_name}}"
    }
   ]
  },
  {
   "title": "Data Writes/Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (sql_instance, database_name) (\n  irate(sqlserver_database_io_write_bytes{sql_instance=~\"$sql_instance\"}[30s])\n)\n",
     "legendFormat": "{{sql_instance}} - {{database_name}}"
    }
   ]
  },
  {
   "title": "Database Read Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (sql_instance, database_name, logicalname, physical_filename) (\n  irate(sqlserver_database_io_read_latency_ms[30s])\n)\n/\nclamp_min(\n  sum by (sql_instance, database_name, logicalname, physical_filename) (\n    irate(sqlserver_database_io_reads[30s])\n  ),\n  1\n)\n",
     "legendFormat": "{{sql_instance}} - {{database_name}} - {{physical_filename}} "
    }
   ]
  },
  {
   "title": "Database Write Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (sql_instance, database_name, logicalname, physical_filename) (\n  irate(sqlserver_database_io_write_latency_ms[30s])\n)\n/\nclamp_min(\n  sum by (sql_instance, database_name, logicalname, physical_filename) (\n    irate(sqlserver_database_io_writes[30s])\n  ),\n  1\n)\n",
     "legendFormat": "{{sql_instance}} - {{database_name}} - {{physical_filename}} "
    }
   ]
  },
  {
   "title": "FlashArray Read Latency (μs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (\n  irate(\n    purefa_volume_performance_latency_usec{\n      instance=~\"$instance\",\n      name=~\".+$sql_instance.+\",\n      dimension=~\"qos_rate_limit_usec_per_read_op|queue_usec_per_read_op|san_usec_per_read_op|service_usec_per_read_op|service_usec_per_read_op_cache_reduction|usec_per_read_op\"\n    }[30s]\n  )\n)\n",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "FlashArray Write Latency (μs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (\n  irate(\n    purefa_volume_performance_latency_usec{\n      instance=~\"$instance\",\n      name=~\".+$sql_instance.+\",\n      dimension=~\"qos_rate_limit_usec_per_write_op|queue_usec_per_write_op|san_usec_per_write_op|service_usec_per_write_op|usec_per_write_op\"\n    }[30s]\n  )\n)\n",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "FlashArray Volume Reads/Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_bandwidth_bytes{ instance=~\"^$instance\", name=~\".+$sql_instance.+\", dimension=\"read_bytes_per_sec\"}) by (instance, name) ",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "FlashArray Volume Write/Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(purefa_volume_performance_bandwidth_bytes{ instance=~\"^$instance\", name=~\".+$sql_instance.+\", dimension=\"write_bytes_per_sec\"}) by (instance, name) ",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "FlashArray Read Average IO Size (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  avg by (instance, name) (\n    avg_over_time(purefa_volume_performance_bandwidth_bytes{\n      instance=~\".*\",\n      name=~\".+$sql_instance.+\",\n      dimension=\"read_bytes_per_sec\"\n    }[30s])\n  )\n)\n/\nclamp_min(\n  (\n    avg by (instance, name) (\n      avg_over_time(purefa_volume_performance_throughput_iops{\n        instance=~\".*\",\n        name=~\".+$sql_instance.+\",\n        dimension=\"reads_per_sec\"\n      }[30s])\n    )\n  ),\n  1\n)\n",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "FlashArray Write Average IO Size (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  avg by (instance, name) (\n    avg_over_time(purefa_volume_performance_bandwidth_bytes{\n      instance=~\".*\",\n      name=~\".+$sql_instance.+\",\n      dimension=\"write_bytes_per_sec\"\n    }[30s])\n  )\n)\n/\nclamp_min(\n  (\n    avg by (instance, name) (\n      avg_over_time(purefa_volume_performance_throughput_iops{\n        instance=~\".*\",\n        name=~\".+$sql_instance.+\",\n        dimension=\"writes_per_sec\"\n      }[30s])\n    )\n  ),\n  1\n)\n",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  }
 ]
}